entrada1 = input()
entrada2 = input()
q1 = int(entrada1.split(' ')[0])
q2 = int(entrada1.split(' ')[1])
q3 = int(entrada1.split(' ')[2])
e1 = int(entrada2.split(' ')[0])
e2 = int(entrada2.split(' ')[1])
e3 = int(entrada2.split(' ')[2])
print((q1 + q2 + q3) - ((e1 + e2 + e3) * 3))
